config/routes.rb
ZappoBilling::Application.routes.draw do

  root :to => "access#index"

  resources :orders do
    resources :products, only: [:index]
    resources :clients, only: [:index]
  end

   resources :shops
  
  match '/orders/new/add_to_cart' => 'orders#add_to_cart'
  match '/orders/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/edit/add_to_cart' => 'orders#add_to_cart'
  match '/orders/:id/edit/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/' => 'orders#update', via: :post
  match '/access' => 'access#index'
  match '/access/login' => 'access#login'
  match '/access/logout' => 'access#logout'
  match '/access/attempt_login' => 'access#attempt_login'

  resources :clients

 

  resources :products do
    resources :orders, only: [:index]
  end

 

  

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :address, :description, :name, :username,  :password, :password_confirmation

  has_secure_password

  
   
  validates :name, presence: true
  validates :description, presence: true
  validates :username, presence: true

  validates_presence_of :password, :on => :create
  

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  before_filter :confirm_logged_in, except: [:new, :create]
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      f
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
 
 <%= errors_messages_for(@shop) %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %><%= params.inspect %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Username</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.name %></td>
    <td><%= shop.description %></td>
    <td><%= shop.address %></td>
    <td><%= shop.username %></td>
    <td><%= shop.password_digest %></td>
    <td><%= link_to 'Show', shop %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
    <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shop.name %>
</p>

<p>
  <b>Description:</b>
  <%= @shop.description %>
</p>

<p>
  <b>Address:</b>
  <%= @shop.address %>
</p>

<p>
  <b>Username:</b>
  <%= @shop.username %>
</p>

<p>
  <b>Password digest:</b>
  <%= @shop.password_digest %>
</p>

<%= params.inspect %>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>