config/routes.rb
ZappoBilling::Application.routes.draw do

  root :to => "access#index"

  resources :orders do
    resources :products, only: [:index]
    resources :clients, only: [:index]
  end

   resources :shops
  
  match '/orders/new/add_to_cart' => 'orders#add_to_cart'
  match '/orders/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/edit/add_to_cart' => 'orders#add_to_cart'
  match '/orders/:id/edit/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/' => 'orders#update', via: :post
  match '/access' => 'access#index'
  match '/access/login' => 'access#login'
  match '/access/logout' => 'access#logout'
  match '/access/attempt_login' => 'access#attempt_login'

  resources :clients

 

  resources :products do
    resources :orders, only: [:index]
  end

 

  

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	before_filter :confirm_logged_in, only: :index
  def index
    @shop = session['shop_id']
  end

  def login
  	
  end

  def logout
  	session["shop_id"] = nil
  	flash[:notice] = "you have been logged out"
  	redirect_to  action: 'login' 
  end

   def attempt_login
   	user = Shop.find_by_username(params["username"]).try(:authenticate, params["password"])
   	if user
  		session["shop_id"] = user.id
  		flash[:notice] = "user successfully logged in"
  		redirect_to action: 'index'
  	else
  		flash[:notice] = "wrong username/password combination"
  		redirect_to action: 'login'
  	end
   end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/index.html.erb
<div >
<h1>Select your option in the menu </h1>
<br><br>
<ul >
	<li><%= link_to "Clients" , clients_path() %><br></li>
	<li><%= link_to "Products" , products_path() %><br></li>
	<li><%= link_to "Orders" , orders_path() %><br></li>
	<li><%= link_to "edit Shop info", edit_shop_path(@shop) %><br></li>
	<li><%= link_to "logout", :action => 'logout' %><br></li>
</ul>
</div>

app/views/access/login.html.erb
<h1>enter your credential to log in your shop or <%= link_to 'Create new shop', new_shop_path %></h1>

<br>
<hr>
<%= notice %>
<hr>

<%= form_tag(action: 'attempt_login') do %>
	<table>
		<tr>
			<td><label>username</label></td>
			<td><%= text_field_tag "username" %></td>
		</tr>
		<tr>
			<td><label>password</label></td>
			<td><%= password_field_tag "password" %></td>
		</tr>
		<tr>
			<td></td>
			<td><%= submit_tag('Login') %></td>
		</tr>
		<br>	
	</table>
<% end -%> <% params.inspect %>