config/routes.rb
ZappoBilling::Application.routes.draw do

  root :to => "access#index"

  resources :orders do
    resources :products, only: [:index]
    resources :clients, only: [:index]
  end

   resources :shops
  
  match '/orders/new/add_to_cart' => 'orders#add_to_cart'
  match '/orders/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/edit/add_to_cart' => 'orders#add_to_cart'
  match '/orders/:id/edit/del_order_line' => 'orders#del_order_line'
  match '/orders/:id/' => 'orders#update', via: :post
  match '/access' => 'access#index'
  match '/access/login' => 'access#login'
  match '/access/logout' => 'access#logout'
  match '/access/attempt_login' => 'access#attempt_login'

  resources :clients

 

  resources :products do
    resources :orders, only: [:index]
  end

 

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :Fname, :Ln

  scope :shopify, lambda {|sid| where("shop_id = ?", sid)}
  validates :Fname, presence: true
  validates :Lname, presence: true
  validates :phonenumber, presence: true,
  						  numericality: true

  has_many :orders
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  before_filter :confirm_logged_in
  def index
    @clients = Client.shopify(sid).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])
    @client.shop_id = sid

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>

<%= errors_messages_for(@client) %>

  <div class="field">
    <%= f.label :Fname %><br />
    <%= f.text_field :Fname %>
  </div>
  <div class="field">
    <%= f.label :Lname %><br />
    <%= f.text_field :Lname %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br />
    <%= f.text_field :phonenumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Fname</th>
    <th>Lname</th>
    <th>Address</th>
    <th>Phonenumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.Fname %></td>
    <td><%= client.Lname %></td>
    <td><%= client.address %></td>
    <td><%= client.phonenumber %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fname:</b>
  <%= @client.Fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @client.Lname %>
</p>

<p>
  <b>Address:</b>
  <%= @client.address %>
</p>

<p>
  <b>Phonenumber:</b>
  <%= @client.phonenumber %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>